name: Java Build and Dependency Check
run-name: ${{ github.actor }} is running tests...
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    name: Build and Dependency Check
    runs-on: ubuntu-latest

  steps:
    - name: Initialize
      run: echo "Job triggered by a ${{ github.event_name }} event."
      
    - name: System Info
      run: echo "This job is now runnion on a ${{ runner.os }} server hosted by GitHub."

    - name: Branch and Repository Info
      run: echo "The Name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Repository Cloned
      run: echo "The ${{ github.repository }} repository has been cloned to the runner."

    - name: Clear Maven Cache
      run: rm -rf $HOME/.m2/repository

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: 19
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        cd testing/
        mvn clean package
      working-directory: ${{ github.workspace }}

    - name: Run Tests
      run: |
        cd testing/
        mvn test
      working-directory: ${{ github.workspace }}

    - name: Job Status
      run: echo "Status report of this job: ${{ job.status }}." 
      
